#:schema node_modules/wrangler/config-schema.json
name = "workerd-modules-sharing-repro"
main = "src/index.js"
compatibility_date = "2024-06-20"

rules = [
  { type = "ESModule", globs = ["**/*.js"], fallthrough = true }
]